analytics: {}
color:
  brandColors:
    - '#fdfdfd'
    - '#87b96a'
    - '#181a26'
    - '#fe6f91'
    - '#aa253d'
  brandStrength: 0.331081
  lightness: 1
  rhythmicContrast: 0.39527
  saturation: 0.5
cta: {}
layout_spectrum: 0.567567
name: ferrisfamilydojo
opengraph: {}
purpose: []
typography_spectrum: 0.05136
